package tests;// Generated by Selenium IDE

import data.AccountData;
import data.DiaryData;
import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.By;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class NodeTest extends TestBase {

    @Test
    public void nodeTest() {
        setupTest();
        AccountData accountData = new AccountData("ruselkomp", "qwerty123");
        DiaryData diaryData = new DiaryData("Свобода", "Исследователи помещают административные реформы Юстиниана в широкий концептуальный контекст, включающий его представление о священном характере императорской власти и идею о необходимости восстановления Римской империи в её прежних границах путём завоевательных войн. Финансирование войн и масштабной строительной деятельности требовало значительных средств. В этом отношении построенная Юстинианом система обеспечивала высокую эффективность. Многие историки отмечают разнообразные системные проблемы, из которых основными являлись коррупция и деградация местного самоуправления. Несмотря на значительные усилия, реформы Юстиниана не смогли переломить сложившиеся тенденции. Юстиниановская система управления и сбора налогов сохранялась в неизменном виде до начала VII века, когда драматические территориальные потери и соответствующее уменьшение доходов потребовали осуществления дальнейших реформ. ");

        applicationManager.getWindowHelper().getSite("https://diary.anek.ws/");
        applicationManager.getWindowHelper().setWinSize(1936, 1056);
        applicationManager.getLoginHelper().login(accountData);
        applicationManager.getDiaryHelper().createDiscussion(diaryData);
        assert applicationManager.getDriver().findElement(By.id("dt741931")).getText().substring(0, 15).equals(diaryData.getText().substring(0, 15));
        applicationManager.getLoginHelper().logout();
    }


}
