// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.io.File;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WikiTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.firefox.bin",
                "D:\\Mozilla\\firefox.exe");
        System.setProperty("webdriver.gecko.driver", "C:\\Users\\rusel\\IdeaProjects\\Tests\\geckodriver.exe");

        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void wiki() {
        driver.get("https://ru.wikipedia.org/");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        {
            WebElement element = driver.findElement(By.linkText("Просмотр кода"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.linkText("Войти")).click();
        driver.findElement(By.id("wpName1")).click();
        driver.findElement(By.cssSelector(".mw-htmlform-field-HTMLTextField:nth-child(1)")).click();
        driver.findElement(By.id("wpName1")).click();
        driver.findElement(By.id("wpName1")).sendKeys("ruselkomp");
        driver.findElement(By.id("wpPassword1")).sendKeys("ruselkomp.ru");
        driver.findElement(By.id("wpPassword1")).sendKeys(Keys.ENTER);
        wait(3);
        driver.findElement(By.linkText("Сообщить об ошибке")).click();
        wait(3);
        driver.findElement(By.cssSelector(".oo-ui-widget:nth-child(2) > .oo-ui-buttonElement-button")).click();
        wait(3);
        driver.findElement(By.id("ooui-4")).sendKeys("Исследователи помещают административные реформы Юстиниана в широкий концептуальный контекст, включающий его представление о священном характере императорской власти и идею о необходимости восстановления Римской империи в её прежних границах путём завоевательных войн. Финансирование войн и масштабной строительной деятельности требовало значительных средств. В этом отношении построенная Юстинианом система обеспечивала высокую эффективность. Многие историки отмечают разнообразные системные проблемы, из которых основными являлись коррупция и деградация местного самоуправления. Несмотря на значительные усилия, реформы Юстиниана не смогли переломить сложившиеся тенденции. Юстиниановская система управления и сбора налогов сохранялась в неизменном виде до начала VII века, когда драматические территориальные потери и соответствующее уменьшение доходов потребовали осуществления дальнейших реформ. ");
        driver.findElement(By.id("ooui-3")).sendKeys("Заглавная");
        driver.findElement(By.linkText("Отправить")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".mw-wiki-logo"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        wait(3);
        driver.findElement(By.linkText("Выйти")).click();
    }

    public void wait(int seconds) {
        try {
            Thread.sleep(seconds * 1000);
        } catch (InterruptedException e) {
            throw new IllegalStateException(e);

        }
    }
}

