// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.io.File;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WikiSendMessageTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    private DefaultClass defaultClass;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.firefox.bin",
                "D:\\Mozilla\\firefox.exe");
        System.setProperty("webdriver.gecko.driver", "C:\\Users\\rusel\\IdeaProjects\\Tests\\geckodriver.exe");

        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        defaultClass = new DefaultClass(driver);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    private void sendMessage(MessageData messageData) {
        driver.findElement(By.linkText("Сообщить об ошибке")).click();
        DefaultClass.wait(3);
        driver.findElement(By.cssSelector(".oo-ui-widget:nth-child(2) > .oo-ui-buttonElement-button")).click();
        DefaultClass.wait(3);
        driver.findElement(By.id("ooui-4")).sendKeys(messageData.getText());
        driver.findElement(By.id("ooui-3")).sendKeys(messageData.getPageName());
        driver.findElement(By.linkText("Отправить")).click();
    }

    @Test

    public void sendMessagetest() {
        AccountData accountData = new AccountData("ruselkomp", "ruselkomp.ru");
        MessageData messageData = new MessageData("Заглавная", "Исследователи помещают административные реформы Юстиниана в широкий концептуальный контекст, включающий его представление о священном характере императорской власти и идею о необходимости восстановления Римской империи в её прежних границах путём завоевательных войн. Финансирование войн и масштабной строительной деятельности требовало значительных средств. В этом отношении построенная Юстинианом система обеспечивала высокую эффективность. Многие историки отмечают разнообразные системные проблемы, из которых основными являлись коррупция и деградация местного самоуправления. Несмотря на значительные усилия, реформы Юстиниана не смогли переломить сложившиеся тенденции. Юстиниановская система управления и сбора налогов сохранялась в неизменном виде до начала VII века, когда драматические территориальные потери и соответствующее уменьшение доходов потребовали осуществления дальнейших реформ. ");

        defaultClass.getSite("https://ru.wikipedia.org/");
        defaultClass.setWinSize(1936, 1056);
        defaultClass.login(accountData);
        sendMessage(messageData);
        defaultClass.doExit();
    }

}

