package tests;// Generated by Selenium IDE

import data.AccountData;
import data.DiscussionData;
import org.junit.After;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class WikiDiscussionTest extends TestBase {

    @Test
    public void discussionTest() {
        setupTest();
        AccountData accountData = new AccountData("ruselkomp", "ruselkomp.ru");
        DiscussionData discussionData = new DiscussionData("Заглавная", "Исследователи помещают административные реформы Юстиниана в широкий концептуальный контекст, включающий его представление о священном характере императорской власти и идею о необходимости восстановления Римской империи в её прежних границах путём завоевательных войн. Финансирование войн и масштабной строительной деятельности требовало значительных средств. В этом отношении построенная Юстинианом система обеспечивала высокую эффективность. Многие историки отмечают разнообразные системные проблемы, из которых основными являлись коррупция и деградация местного самоуправления. Несмотря на значительные усилия, реформы Юстиниана не смогли переломить сложившиеся тенденции. Юстиниановская система управления и сбора налогов сохранялась в неизменном виде до начала VII века, когда драматические территориальные потери и соответствующее уменьшение доходов потребовали осуществления дальнейших реформ. ");

        applicationManager.getWindowHelper().getSite("https://ru.wikipedia.org/");
        applicationManager.getWindowHelper().setWinSize(1936, 1056);
        applicationManager.getLoginHelper().login(accountData);
        applicationManager.getDiscussionHelper().createDiscussion(discussionData);
        applicationManager.getLoginHelper().logout();
    }
    @After
    public void tearDown() {
        applicationManager.tearDown();
    }
}
